### ISSUE TITLE
Blog Previewing

### ISSUE THREAD

**Issue by joelturnbull** [gaslight/gaslight#73]
Want a true preview of the post before publishing. Right now we have the active admin show page, and the epic editor preview. Our blog CSS isn't represented in those.

**Comment by cdmwebs** [comment]
It is now! #173

**Comment by joelturnbull** [comment]
Can I ship it?

**Comment by cdmwebs** [comment]
I don't see why not!



--

Chris Moore | CEO | Gaslight

m: 513.201.7829



chrism@teamgaslight.com



http://teamgaslight.com



http://facebook.com/teamgaslight


http://twitter.com/teamgaslight

**Comment by st23am** [comment]
http://media.giphy.com/media/VLoN2iW8ii3wA/giphy.gif
